# Generated by Django 5.1.6 on 2025-05-05 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pedidoplato',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='plato',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='pedido',
            name='plato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.plato'),
        ),
    ]
